### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by lquintanac** [aigora/twIE_2021-j_a_y_#2]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by oscarperpinan** [comment]
El código del menú debe estar contenido en un fichero con extensión .c

**Comment by orgynmobs** [comment]
Cuando lo hagáis, cerrad la issue y la milestone si esta está al 100%
